changes to Cards table
PDG94/simpleservice pull request #127
Opened 2023-02-22 22:23 UTC by Larva-Soup

Por sugerencia de Pedro modifiqué Card en vez de volver a implementar Service, sí es más fácil y Service de paso ya no existe (también borré un archivo que solo utilicé para hacer unas pruebas y que se me fue en un commit)

2023-02-22 22:44 UTC, PDG94 approved these changes

2023-02-23 05:25 UTC, PDG94 requested changes
puede romper, por ahora que no se apruebe hasta que chris este seguro

2023-02-23 16:45 UTC, PDG94 approved these changes

2023-02-23 17:11 UTC, Edwards0307 approved these changes

2023-02-23 17:12 UTC, merged